"""initial_schema

Revision ID: ee8bde7caa8b
Revises: 8021b4e2cf02
Create Date: 2025-12-07 21:27:04.856781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee8bde7caa8b'
down_revision: Union[str, None] = '8021b4e2cf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
